### ISSUE TITLE
Alpn

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/StreamExtended#1]
There seem to be a problem with ClientHelloAlpnAdderStream and ServerHelloAlpnAdderStream. AuthenticateAsClientAsync/AuthenticateAsServerAsync fails when calling with this stream. 

Even though we can see that the servers respond with positive alpn h2 in its initial handshake with our modified client hello, something is happening inside that makes the Authentication fail in subsequent internal steps in AuthenticateAsClientAsync/AuthenticateAsServerAsync. 

@honfika I know you mentioned this before. I initially thought it could be because we didn't yet support HTTP/2 preface in the proxy. But I think that still the call shouldn't fail, since HTTP/2 traffic will start only after AuthenticateAsClientAsync/AuthenticateAsServerAsync is complete.

**Comment by justcoding121** [comment]
Apparently the issue is message hash mismatch as observed in comment from MS employee
https://github.com/dotnet/corefx/issues/4721#issuecomment-313239925

**Comment by cesarblum** [comment]
Yep, check here: https://tools.ietf.org/html/rfc5246#section-7.4.9

Both ends keep hashes of every message exchanged during the handshake. If you intercept the ServerHello message from `SslStream` and change it, the client will compute a hash for that message that's different than what the server computed before sending it.

**Comment by honfika** [comment]
Then it should be changed, too:)

Ohh, that is already encrypted. Then is is harder.

**Comment by justcoding121** [comment]
@honfika I noted that the call fails at below line for AuthenticateAsServer
https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/Security/SslState.cs#L810

At that point its about to finish the negotiation. The SslStream is a wrapper around Windows SChannel. So I think the hash itself is computed and verified by SChannel with native calls to it. 

We are stuck with two options either rewrite an updated SslStream (in [System.Net.Security.sln](https://github.com/dotnet/corefx/tree/master/src/System.Net.Security)) with ALPN support as done with the PR in corefx (also for other platforms & Mono) or recompute the hash like you said which seems tedious or may be even impossible. 

Another option may be to use reflection to insert ALPN extension on SslStream, windows SChannel already supports it. But not sure about other platforms.
