### ISSUE TITLE
Support Task Cancellation

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/StreamExtended#20]
We need to support async task cancellation by accepting a CancellationToken in constructors of all our async supporting objects.

https://github.com/justcoding121/Titanium-Web-Proxy/issues/410

**Comment by honfika** [comment]
I've added CancellationToken parameters to the methods as usual in .NET framework, they are optional parameters. Is this ok?

**Comment by justcoding121** [comment]
Yes. Looks good.
