### ISSUE TITLE
Use Dictionary instead of List for Extensions

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/StreamExtended#5]
I think it would be good idea to use a Dictionary for extensions instead of a list. This will enhance performance little bit. Would be particularly useful in below line. 

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L236

Also I think we can add an Enum to represent all extensions. For example something like

```
public enum ExtensionCode
{
 ServerName = 0,
 MaxFragmentLength = 1 
....
}
```

So that we can return a `Dictionary<ExtensionCode, SslExtension>` in below line.
https://github.com/justcoding121/StreamExtended/blob/develop/StreamExtended/SslTools.cs#L137

@honfika

**Comment by honfika** [comment]
Implemented, but this needs a new stable version or TWP, too since it will fail if somebody upgrades the StreamExtended package to the latest.
